CREATE TABLE [dbo].[TB_LOGIN](
	[ID] INT IDENTITY NOT NULL,
	[IdUser] INT NOT NULL,
	[Username] VARCHAR(30) NOT NULL,
	[Senha] VARCHAR(32) NOT NULL,
	[Status] BIT NOT NULL, -- (Ativo/Inativo)
	CONSTRAINT [PK_LOGIN] PRIMARY KEY([ID]),
	CONSTRAINT [FK_LOGIN_USER] FOREIGN KEY([IdUser]) REFERENCES TB_USER([ID])
)
GO