USE SCOPIO
GO

-- INSERT TRIBO
INSERT INTO TB_TRIBO VALUES(NULL, 'CDP EFINANCE', 1)
INSERT INTO TB_TRIBO VALUES(NULL, 'CDP RDV', 1)
INSERT INTO TB_TRIBO VALUES(NULL, 'CDS BRINKS', 1)
INSERT INTO TB_TRIBO VALUES(NULL, 'CDS EVOLUTIVAS MAPFRE', 1)
INSERT INTO TB_TRIBO VALUES(NULL, 'CDS FINAMAX', 1)
INSERT INTO TB_TRIBO VALUES(NULL, 'CDS NN MAPFRE', 1)
INSERT INTO TB_TRIBO VALUES(NULL, 'CDS PASSARELA', 1)
INSERT INTO TB_TRIBO VALUES(NULL, 'CDS SEQUOIA', 1)
INSERT INTO TB_TRIBO VALUES(NULL, 'CDS UNIBANCO', 1)
INSERT INTO TB_TRIBO VALUES(NULL, 'CONSULTORIA', 1)
INSERT INTO TB_TRIBO VALUES(NULL, 'CSS MAPFRE', 1)
INSERT INTO TB_TRIBO VALUES(NULL, 'FORMAÇÃO', 1)
INSERT INTO TB_TRIBO VALUES(NULL, 'OPERAÇÃO', 1)
GO

-- INSERT PAIS
INSERT INTO TB_PAIS VALUES('BRASIL', 'BRA')
INSERT INTO TB_PAIS VALUES('ESTADOS UNIDOS', 'EUA')
GO

-- INSERT UNIDADE
INSERT INTO TB_UNIDADE VALUES(1, 'VICERI OSORIO', 'SP')
INSERT INTO TB_UNIDADE VALUES(1, 'VICERI JOBIM', 'SP')
GO

-- INSERT SQUAD
INSERT INTO TB_SQUAD VALUES(1, 12, '','LEMURES MUTUALISTAS', 1)
INSERT INTO TB_SQUAD VALUES(1, 12, '','BUG HUNTERS', 1)
INSERT INTO TB_SQUAD VALUES(1, 12, '','NERD BUNKERS', 1)
INSERT INTO TB_SQUAD VALUES(1, 12, '','ALFA NOOB', 1)
GO

-- INSERT PAPEL
INSERT INTO TB_PAPEL VALUES('ESTAGIÁRIO DE PROGRAMAÇÃO TREINEE', 'EP', 0)
INSERT INTO TB_PAPEL VALUES('ESTAGIÁRIO DE PROGRAMAÇÃO JÚNIOR', 'EP', 0)
INSERT INTO TB_PAPEL VALUES('PROGRAMADOR TREINEE', 'PR', 1)
INSERT INTO TB_PAPEL VALUES('PROGRAMADOR JÚNIOR', 'PR', 1)
INSERT INTO TB_PAPEL VALUES('PROGRAMADOR SÊNIOR', 'PR', 2)
INSERT INTO TB_PAPEL VALUES('PROGRAMADOR PLENO', 'PR', 3)
INSERT INTO TB_PAPEL VALUES('ANALISTA DE NEGÓCIOS JÚNIOR', 'NA', 4)
INSERT INTO TB_PAPEL VALUES('ANALISTA DE NEGÓCIOS SÊNIOR', 'NA', 5)
INSERT INTO TB_PAPEL VALUES('ANALISTA DE NEGÓCIOS PLENO', 'NA', 6)
INSERT INTO TB_PAPEL VALUES('ANALISTA DE QUALIDADE JÚNIOR', 'AQ', 4)
INSERT INTO TB_PAPEL VALUES('ANALISTA DE QUALIDADE SÊNIOR', 'NA', 5)
INSERT INTO TB_PAPEL VALUES('ANALISTA DE QUALIDADE PLENO', 'NA', 6)
INSERT INTO TB_PAPEL VALUES('ANALISTA DE SISTEMAS JÚNIOR', 'AS', 4)
INSERT INTO TB_PAPEL VALUES('ANALISTA DE SISTEMAS SÊNIOR', 'NA', 5)
INSERT INTO TB_PAPEL VALUES('ANALISTA DE SISTEMAS PLENO', 'NA', 6)
INSERT INTO TB_PAPEL VALUES('ANALISTA PROGRAMADOR JÚNIOR', 'AP', 4)
INSERT INTO TB_PAPEL VALUES('ANALISTA DE PROGRAMADOR SÊNIOR', 'NA', 5)
INSERT INTO TB_PAPEL VALUES('ANALISTA DE PROGRAMADOR PLENO', 'NA', 6)
INSERT INTO TB_PAPEL VALUES('ARQUITETO DE TESTES JÚNIOR', 'AT', 7)
INSERT INTO TB_PAPEL VALUES('ARQUITETO DE TESTES SÊNIOR', 'AT', 8)
INSERT INTO TB_PAPEL VALUES('ARQUITETO DE TESTES PLENO', 'AT', 9)
INSERT INTO TB_PAPEL VALUES('ARQUITETO UX/UI JÚNIOR', 'AU', 7)
INSERT INTO TB_PAPEL VALUES('ARQUITETO UX/UI SÊNIOR', 'AU', 8)
INSERT INTO TB_PAPEL VALUES('ARQUITETO UX/UI PLENO', 'AU', 9)
INSERT INTO TB_PAPEL VALUES('ENGENHEIRO DE SOFTWARE JÚNIOR', 'ES', 7)
INSERT INTO TB_PAPEL VALUES('ENGENHEIRO DE SOFTWARE SÊNIOR', 'ES', 8)
INSERT INTO TB_PAPEL VALUES('ENGENHEIRO DE SOFTWARE PLENO', 'ES', 9)
INSERT INTO TB_PAPEL VALUES('COORDENADOR DE DESENVOLVIMENTO JÚNIOR', 'CD', 10)
INSERT INTO TB_PAPEL VALUES('COORDENADOR DE DESENVOLVIMENTO SÊNIOR', 'CD', 11)
INSERT INTO TB_PAPEL VALUES('COORDENADOR DE DESENVOLVIMENTO PLENO', 'CD', 12)
INSERT INTO TB_PAPEL VALUES('GERENTE DE TI JÚNIOR', 'GT', 13)
INSERT INTO TB_PAPEL VALUES('GERENTE DE TI SÊNIOR', 'GT', 14)
INSERT INTO TB_PAPEL VALUES('GERENTE DE TI PLENO', 'GT', 15)
INSERT INTO TB_PAPEL VALUES('RECURSOS HUMANOS', 'RH', 16)
INSERT INTO TB_PAPEL VALUES('CEO', 'CO', 17)
GO

-- INSERT USER
INSERT INTO TB_USER VALUES(2, NULL, 'ALEX BARLETTA ARAÚJO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(18, NULL, 'AMANDA MAYARA DE ARAUJO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(18, NULL, 'ANA CLARA MARSON RIOS BORDINHON', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(16, NULL, 'ANDERSON DE CARVALHO BERNABÉ', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(32, NULL, 'ANDERSON SOLDEIRA DE LIMA CAVALCANTE', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(11, NULL, 'AULES RONI JOBSTRAIBIZER', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'CALÉO DE ANTONIO CACIANO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(17, NULL, 'CLOTER GONÇALVES BARBOSA JUNIOR', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(14, NULL, 'DANIEL MEIRELES TOMAZINI', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(14, NULL, 'DANIELA OLIVEIRA FRANCISCO TEIXEIRA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(12, NULL, 'DANILO CESAR DE SOUZA FERREIRA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(17, NULL, 'DELEON HENRIQUE DA SILVA PINTO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'DENISE NOGUEIRA DOS SANTOS', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(9, NULL, 'EDNEI BETTI', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(26, NULL, 'EDUARDO ALBERTO DO SANTOS', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(17, NULL, 'ELAINE VIANA COSTA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(14, NULL, 'EMERSON CARLOS DUARTE', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(18, NULL, 'EVAIR PEREIRA SOUSA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(17, NULL, 'EVANDRO RIBEIRO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(7, NULL, 'EVERTON LIMA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(1, NULL, 'EVERTON LUIZ FERREIRA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(16, NULL, 'FABIO MASSARETTO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'FÁBIO VIEIRA GONÇALVES', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(12, NULL, 'FELIPE DE MELLO OLIVEIRA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'FERNANDA LUÍZA CONTI', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(21, NULL, 'FERNANDA MARIA DUARTE VIEIRA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(16, NULL, 'FERNANDO ALCÂNTARA GARCIA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(14, NULL, 'FERNANDO BERSTECHER AJLUNE', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'FERNANDO JUNIO DA SILVA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(26, NULL, 'FERNANDO MENDES', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'FILIPE DE OLIVEIRA RIBEIRO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(14, NULL, 'FILIPE PEREIRA COLANERI', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(18, NULL, 'GABRIEL BRUNO TRALDI', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(4, NULL, 'GABRIEL WILLIAM GALDINO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(16, NULL, 'GEOVANI LIMA AZEVEDO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(12, NULL, 'GESSIANE DA SILVIA MARTINELLE', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'GIOVANA SELEIO VALINI', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'GLÉBER MICHEL ALVES SCHIAVO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(16, NULL, 'GREGORI BRUNO FELICIO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'GUILHERME BORDALLO DE ALMEIDA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(14, NULL, 'GUILHERME CESTAROLLI SELEGUIM', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(15, NULL, 'GUSTAVO SERRACCHIANI FERRARI', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(29, NULL, 'HENRIQUE FANTATHO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'ISAC DANIEL FILDELFLAVIO PETINATE', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(17, NULL, 'ITALO BIGUZI DUARTE', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'JHONATAN VINÍCIUS MARTINS DOS SANTOS', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(16, NULL, 'JULIO CÉSAR MONTALVÃO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(10, NULL, 'KAIQUE GUSTAVO RIBEIRO DO PRADO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(14, NULL, 'LEANDRO CODARIN', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(1, NULL, 'LEANDRO MARQUES DE OLIVEIRA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(17, NULL, 'LEILA SANTANA FERREIRA FIGUEREDO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(16, NULL, 'LUCAS MARQUES DA SILVA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(1, NULL, 'LUCAS TÚMOLO CONTESINI', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(10, NULL, 'LUCAS VENDRAMIN ANTUNES', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(11, NULL, 'LUCIANA MARTINS PONTEL BAHIA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(17, NULL, 'LUCIO FLAVIO FRANSOIA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'LUÍS ANTONIO PRADO LANÇA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(17, NULL, 'LUIZ CARLOS CECATTI JÚNIOR', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(11, NULL, 'MARA CRISTINA DA ROSA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(18, NULL, 'MARCO AURELIO DE SOUZA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(18, NULL, 'MARIO JORGE DE ARAUJO BARBOSA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(1, NULL, 'MATEUS AUGUSTO DO AMARAL', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'MATEUS GONÇALVES BRITO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(1, NULL, 'MATHEUS BIO SALLES', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(18, NULL, 'MIKAERI OHANA ESTEVAM CANDIDO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(18, NULL, 'MURILO EDUARDO BACAGINI SANTOS', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(18, NULL, 'NICOLAS TOSATTI', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(17, NULL, 'OTAVIO AUGUSTO TOLEDO DE PAULA CIPRO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(15, NULL, 'PABLO ZAMPA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(23, NULL, 'PAULO ROGÉRIO SPIANDORIM MATTIUZZO  ', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'PEDRO DE SOUZA MORAES', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'PEDRO MIETTO BRUINI', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(12, NULL, 'PEDRO OCTAVIO RODRIGUES DE ANDRADE', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(17, NULL, 'RAFAEL DE MOURA ALVES', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(1, NULL, 'RAFAEL LINO DOS SANTOS', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(14, NULL, 'RAFAEL ZANCANI FERCONDINI', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(30, NULL, 'RAFAELA GIROTTE SAMPAIO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(18, NULL, 'RENAN TEIXEIRA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(26, NULL, 'RICARDO ALVES DE SOUZA FRANCISCO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(17, NULL, 'RICARDO APARECIDO GARBATI', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(14, NULL, 'RICARDO CRISTIANO TAPIA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(14, NULL, 'RICARDO MARCEL GIARETTA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(8, NULL, 'RICARDO MEAN', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(18, NULL, 'RICARDO RAMOS', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(17, NULL, 'RODRIGO ALVES FERREIRA DE BRITO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(16, NULL, 'SERGIO DO CARMO TORRES', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(17, NULL, 'SILVIA CRISTINA AROUCHE', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'STEPHANIE BIANCA BRESCANCIN', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(14, NULL, 'THIAGO MANSONETTO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(16, NULL, 'TIAGO DE OLIVEIRA TEIXEIRA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(12, NULL, 'TIAGO HENRIQUE BERNARDO', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(16, NULL, 'VALDEMIR PRAXEDES TRINDADE', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(2, NULL, 'VANDERLEI NERES DA SILVA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(1, NULL, 'VANDERLEY NERES DE SILVA', NULL, NULL, 1)
INSERT INTO TB_USER VALUES(18, NULL, 'WILLIAM HARTUNG', NULL, NULL, 1)
GO

-- CRIA ASSOCIAÇÃO ENTRE USUÁRIO E LOGIN
DECLARE @HASH VARCHAR(32);
SET @HASH = '123'
SET @HASH = CONVERT(VARCHAR(32), HashBytes('MD5', @HASH), 2)
SET @HASH = CONVERT(VARCHAR(32), HashBytes('MD5', @HASH), 2)
INSERT INTO [TB_LOGIN](IdUser, Username, Senha)
VALUES (38,'ggleber',@HASH)
GO

DECLARE @HASH VARCHAR(32);
SET @HASH = '123'
SET @HASH = CONVERT(VARCHAR(32), HashBytes('MD5', @HASH), 2)
SET @HASH = CONVERT(VARCHAR(32), HashBytes('MD5', @HASH), 2)
INSERT INTO [TB_LOGIN](IdUser, Username, Senha)
VALUES (62,'mamaral',@HASH)
GO

DECLARE @HASH VARCHAR(32);
SET @HASH = '123'
SET @HASH = CONVERT(VARCHAR(32), HashBytes('MD5', @HASH), 2)
SET @HASH = CONVERT(VARCHAR(32), HashBytes('MD5', @HASH), 2)
INSERT INTO [TB_LOGIN](IdUser, Username, Senha)
VALUES (25,'fconti',@HASH)
GO

DECLARE @HASH VARCHAR(32);
SET @HASH = '123'
SET @HASH = CONVERT(VARCHAR(32), HashBytes('MD5', @HASH), 2)
SET @HASH = CONVERT(VARCHAR(32), HashBytes('MD5', @HASH), 2)
INSERT INTO [TB_LOGIN](IdUser, Username, Senha)
VALUES (1,'abarletta',@HASH)
GO

DECLARE @HASH VARCHAR(32);
SET @HASH = '123'
SET @HASH = CONVERT(VARCHAR(32), HashBytes('MD5', @HASH), 2)
SET @HASH = CONVERT(VARCHAR(32), HashBytes('MD5', @HASH), 2)
INSERT INTO [TB_LOGIN](IdUser, Username, Senha)
VALUES (7,'ccaciano',@HASH)
GO

