-- VIEW ASSOCIAÇÃO DE MENTOR {TRIBO / SQUAD}
CREATE VIEW vwMentor AS
SELECT TB_MENTOR_TRIBO.ID AS [ID_T], TB_MENTOR_TRIBO.IdUser AS [MENTOR_TRIBO],
TB_MENTOR_TRIBO.IdTribo, TB_MENTOR_SQUAD.ID AS [ID_S],
TB_MENTOR_SQUAD.IdUser AS [MENTOR_SQUAD], TB_MENTOR_SQUAD.IdSquad
FROM TB_USER
INNER JOIN TB_MENTOR_TRIBO ON
TB_USER.ID = TB_MENTOR_TRIBO.ID
INNER JOIN TB_MENTOR_SQUAD ON
TB_USER.ID = TB_MENTOR_SQUAD.ID
GO
