CREATE TABLE [dbo].[TB_MEMBRO_TRIBO](
	[ID] INT IDENTITY NOT NULL,
	[IdUser] INT NOT NULL,
	[IdTribo] INT NULL,
	CONSTRAINT [PK_MEMBRO_TRIBO] PRIMARY KEY([ID]),
	CONSTRAINT [FK_MEMBRO_TRIBO_USER] FOREIGN KEY([IdUser]) REFERENCES TB_USER([ID]),
	CONSTRAINT [FK_MEMBRO_TRIBO_TRIBO] FOREIGN KEY([IdTribo]) REFERENCES TB_TRIBO([ID])
)
GO