CREATE TABLE [dbo].[TB_MENTOR_SQUAD](
    [ID] INT IDENTITY NOT NULL,
    [IdSquad] INT NOT NULL,
    [IdMentor] INT NOT NULL,
    CONSTRAINT [PK_MENTORSQUAD] PRIMARY KEY([ID]),
    CONSTRAINT [FK_MENTORSQUAD_SQUAD] FOREIGN KEY([IdSquad]) REFERENCES TB_SQUAD([ID]),
    CONSTRAINT [FK_MENTORSQUAD_MENTOR] FOREIGN KEY([IdMentor]) REFERENCES TB_MENTOR([ID])
)
GO