CREATE TABLE [dbo].[TB_MENTOR_TRIBO](
    [ID] INT IDENTITY NOT NULL,
    [IdTribo] INT NOT NULL,
    [IdMentor] INT NOT NULL,
    CONSTRAINT [PK_MENTORTRIBO] PRIMARY KEY([ID]),
    CONSTRAINT [FK_MENTORTRIBO_TRIBO] FOREIGN KEY([IdTribo]) REFERENCES TB_TRIBO([ID]),
    CONSTRAINT [FK_MENTORTRIBO_MENTOR] FOREIGN KEY([IdMentor]) REFERENCES TB_MENTOR([ID])
)
GO