CREATE TABLE [dbo].[TB_USER](
	[ID] INT IDENTITY NOT NULL,
	[IdPapel] INT NOT NULL,
	[IdNivel] INT NOT NULL,
	[IdResponsabilidade] INT,
	[Avatar] VARCHAR(200) NULL,
	[Nome] VARCHAR(50) NOT NULL,
	[Email] VARCHAR(100) NULL,
	[Tel] VARCHAR(14) NULL,
	[Status] BIT NOT NULL, -- (Ativo/Inativo)
	CONSTRAINT [PK_USER] PRIMARY KEY([ID]),
	CONSTRAINT [FK_USER_PAPEL] FOREIGN KEY([IdPapel]) REFERENCES TB_PAPEL([ID]),
	CONSTRAINT [FK_USER_NVPAPEL] FOREIGN KEY([IdNivel]) REFERENCES TB_NVPAPEL([ID]),
	CONSTRAINT [FK_USER_RESPONSABILIDADE] FOREIGN KEY ([IdResponsabilidade]) REFERENCES TB_RESPONSABILIDADE([ID])
)
GO