CREATE DATABASE SCOPIO
GO

USE SCOPIO
GO

/*
SELECT *
FROM TB_LOGIN
GO

SELECT *
FROM TB_USER
GO
*/

/*
INSERT INTO TB_PAPEL VALUES('DEV JR',0),('DEV P',1), ('DEV S',2), ('ANALISTA SIS',3)
GO*/

CREATE TABLE [dbo].[TB_PAPEL](
	[ID] INT IDENTITY NOT NULL,
	[Nome] VARCHAR(40) NOT NULL,
	[Nivel] SMALLINT NOT NULL,
	CONSTRAINT [PK_PAPEL] PRIMARY KEY([ID])
)
GO

CREATE TABLE [dbo].[TB_USER](
	[ID] INT IDENTITY NOT NULL,
	[IdPapel] INT NOT NULL,
	--[Foto] VARCHAR(200),
	[Nome] VARCHAR(50) NOT NULL,
	[Email] VARCHAR(100) NULL,
	[Tel] VARCHAR(14) NULL,
	[Status] BIT NOT NULL, -- (Ativo/Inativo)
	CONSTRAINT [PK_USER] PRIMARY KEY([ID]),
	CONSTRAINT [FK_USER_PAPEL] FOREIGN KEY([IdPapel]) REFERENCES TB_PAPEL([ID])
)
GO

CREATE TABLE [dbo].[TB_LOGIN](
	[ID] INT IDENTITY NOT NULL,
	[IdUser] INT NOT NULL,
	[Username] VARCHAR(30) NOT NULL,
	[Senha] VARCHAR(32) NOT NULL,
	CONSTRAINT [PK_LOGIN] PRIMARY KEY([ID]),
	CONSTRAINT [FK_LOGIN_USER] FOREIGN KEY([IdUser]) REFERENCES TB_USER([ID])
)
GO

CREATE TABLE [dbo].[TB_PAIS](
	[ID] INT IDENTITY NOT NULL,
	[Nome] VARCHAR(50) NOT NULL,
	[Sigla] CHAR(3) NOT NULL,
	CONSTRAINT [PK_PAIS] PRIMARY KEY([ID])
)
GO

CREATE TABLE [dbo].[TB_UNIDADE](
	[ID] INT IDENTITY NOT NULL,
	[IdPais] INT NOT NULL,
	[Nome] VARCHAR(50) NOT NULL,
	CONSTRAINT [PK_UNIDADE] PRIMARY KEY([ID]),
	CONSTRAINT [FK_UNIDADE_PAIS] FOREIGN KEY([IdPais]) REFERENCES TB_PAIS([ID])
)
GO

CREATE TABLE [dbo].[TB_TRIBO](
	[ID] INT IDENTITY NOT NULL,
	[IdUnidade] INT NOT NULL,
	--[Logo] VARCHAR(200),
	[Nome] VARCHAR(50) NOT NULL,
	[Status] BIT NOT NULL, -- (Ativo/Inativo)
	CONSTRAINT [PK_TRIBO] PRIMARY KEY([ID]),
	CONSTRAINT [FK_TRIBO_UNIDADE] FOREIGN KEY([IdUnidade]) REFERENCES TB_UNIDADE([ID])
)
GO

CREATE TABLE [dbo].[TB_SQUAD](
	[ID] INT IDENTITY NOT NULL,
	[IdUnidade] INT NOT NULL,
	[IdTribo] INT NULL,
	--[Logo] VARCHAR(200),
	[Nome] VARCHAR(50) NOT NULL,
	[Status] BIT NOT NULL, -- (Ativo/Inativo)
	CONSTRAINT [PK_SQUAD] PRIMARY KEY([ID]),
	CONSTRAINT [FK_SQUAD_TRIBO] FOREIGN KEY([IdTribo]) REFERENCES TB_TRIBO([ID]),
	CONSTRAINT [FK_SQUAD_UNIDADE] FOREIGN KEY([IdUnidade]) REFERENCES TB_UNIDADE([ID])
)
GO

CREATE TABLE [dbo].[TB_MEMBRO](
	[ID] INT IDENTITY NOT NULL,
	[IdUser] INT NOT NULL,
	[IdSquad] INT NULL,
	CONSTRAINT [PK_MEMBRO] PRIMARY KEY([ID]),
	CONSTRAINT [FK_MEMBRO_USER] FOREIGN KEY([IdUser]) REFERENCES TB_USER([ID]),
	CONSTRAINT [FK_MEMBRO_SQUAD] FOREIGN KEY([IdSquad]) REFERENCES TB_SQUAD([ID])
)
GO

CREATE TABLE [dbo].[TB_MENTOR_TRIBO](
	[ID] INT IDENTITY NOT NULL,
	[IdTribo] INT NOT NULL,
	[IdMembro] INT NOT NULL,
	CONSTRAINT [PK_MENTORTRIBO] PRIMARY KEY([ID]),
	CONSTRAINT [FK_MENTORTRIBO_TRIBO] FOREIGN KEY([IdTribo]) REFERENCES TB_TRIBO([ID]),
	CONSTRAINT [FK_MENTORTRIBO_MEMBRO] FOREIGN KEY([IdMembro]) REFERENCES TB_MEMBRO([ID])
)
GO

CREATE TABLE [dbo].[TB_MENTOR_SQUAD](
	[ID] INT IDENTITY NOT NULL,
	[IdSquad] INT NOT NULL,
	[IdMembro] INT NOT NULL,
	CONSTRAINT [PK_MENTORSQUAD] PRIMARY KEY([ID]),
	CONSTRAINT [FK_MENTORSQUAD_SQUAD] FOREIGN KEY([IdSquad]) REFERENCES TB_SQUAD([ID]),
	CONSTRAINT [FK_MENTORSQUAD_MEMBRO] FOREIGN KEY([IdMembro]) REFERENCES TB_MEMBRO([ID])
)
GO

/*
CREATE TABLE [dbo].TB_(

)
GO
*/