CREATE TABLE [dbo].[TB_MENTOR_SQUAD](
	[ID] INT IDENTITY NOT NULL,
	[IdSquad] INT NOT NULL,
	[IdMembro] INT NOT NULL,
	CONSTRAINT [PK_MENTORSQUAD] PRIMARY KEY([ID]),
	CONSTRAINT [FK_MENTORSQUAD_SQUAD] FOREIGN KEY([IdSquad]) REFERENCES TB_SQUAD([ID]),
	CONSTRAINT [FK_MENTORSQUAD_MEMBRO] FOREIGN KEY([IdMembro]) REFERENCES TB_MEMBRO([ID])
)
GO