CREATE TABLE [dbo].[TB_MENTOR_TRIBO](
	[ID] INT IDENTITY NOT NULL,
	[IdTribo] INT NOT NULL,
	[IdMembro] INT NOT NULL,
	CONSTRAINT [PK_MENTORTRIBO] PRIMARY KEY([ID]),
	CONSTRAINT [FK_MENTORTRIBO_TRIBO] FOREIGN KEY([IdTribo]) REFERENCES TB_TRIBO([ID]),
	CONSTRAINT [FK_MENTORTRIBO_MEMBRO] FOREIGN KEY([IdMembro]) REFERENCES TB_MEMBRO([ID])
)
GO