CREATE TABLE [dbo].[TB_SQUAD](
	[ID] INT IDENTITY NOT NULL,
	[IdUnidade] INT NOT NULL,
	[IdTribo] INT NULL,
	--[Logo] VARCHAR(200),
	[Nome] VARCHAR(50) NOT NULL,
	[Status] BIT NOT NULL, -- (Ativo/Inativo)
	CONSTRAINT [PK_SQUAD] PRIMARY KEY([ID]),
	CONSTRAINT [FK_SQUAD_TRIBO] FOREIGN KEY([IdTribo]) REFERENCES TB_TRIBO([ID]),
	CONSTRAINT [FK_SQUAD_UNIDADE] FOREIGN KEY([IdUnidade]) REFERENCES TB_UNIDADE([ID])
)
GO